version: '3'
services:
  gpt-sovits:
    image: breakstring/gpt-sovits:latest
    ports:
      - "9880:9880"
      - "9871:9871"
      - "9872:9872"
      - "9873:9873"
      - "9874:9874"
    volumes:
      - ./model:/workspace/model
    command: >
      python api.py 
      -dr "model/pm/既然罗莎莉亚说足迹上有元素力，用元素视野应该能很清楚地看到吧。.wav" 
      -dt "既然罗莎莉亚说足迹上有元素力，用元素视野应该能很清楚地看到吧。" 
      -dl "zh" 
      -d "cuda" 
      -s model/pm/派蒙-平静_e25_s11925.pth
      -g model/pm/派蒙-平静-e10.ckpt
    shm_size: 16G
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: "all"
            capabilities: [gpu]