version: '3'
services:
  gpt-sovits:
    image: breakstring/gpt-sovits:latest
    ports:
      - "9880:9880"
      - "9871:9871"
      - "9872:9872"
      - "9873:9873"
      - "9874:9874"
    volumes:
      - ./model:/workspace/model
    command: >
      python api.py 
      -dr "model/kll/参考音频/娜塔莎姐姐说克拉拉也是医生呢，是机器伙伴的医生。.wav" 
      -dt "娜塔莎姐姐说克拉拉也是医生呢，是机器伙伴的医生。" 
      -dl "zh" 
      -d "cuda" 
      -s model/kll/克拉拉_e15_s1050.pth
      -g model/kll/克拉拉-e10.ckpt
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]