version: '3'
services:
  yt-dlp:
    image: jauderho/yt-dlp
    volumes:
      - ../../output:/app
    environment:
      - HTTP_PROXY=http://host.docker.internal:7890
      - HTTPS_PROXY=http://host.docker.internal:7890