version: '3'
services:
  ffmpeg:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    volumes:
      - ../../output:/app
    networks:
      default:
        aliases:
          - ffmpeg
networks:
  default:


